seed: 2022
field_separator: "\t"
source_domain:
  dataset: "/home/dmeher/datasets/AmazonBooks/AmazonBooks"
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: rating
  load_col:
    inter: [user_id, item_id, rating]
  user_inter_num_interval: "[10,inf)"
  item_inter_num_interval: "[10,inf)"
  val_interval:
    rating: "[3,inf)"
  drop_filter_field: True

target_domain:
  dataset: "/home/dmeher/datasets/AmazonMov/AmazonMov"
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  RATING_FIELD: rating
  TIME_FIELD: timestamp
  NEG_PREFIX: neg_
  LABEL_FIELD: rating
  load_col:
    inter: [user_id, item_id, rating]
  user_inter_num_interval: "[10,inf)"
  item_inter_num_interval: "[10,inf)"
  val_interval:
    rating: "[3,inf)"
  drop_filter_field: True

epochs: 5
train_batch_size: 4096
eval_batch_size: 409600
valid_metric: RMSE
embedding_size: 64
eval_setting: TO_LS,full
metrics: ['RMSE', 'MAE']
eval_args:
        mode: labeled
        split_valid: {'LS':'valid_and_test'}
